
var __cov_3ngYgTb6MAkCzS6_ii_tJQ = (Function('return this'))();
if (!__cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__) { __cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__ = {}; }
__cov_3ngYgTb6MAkCzS6_ii_tJQ = __cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__;
if (!(__cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'])) {
   __cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":93,"loc":{"start":{"line":93,"column":19},"end":{"line":93,"column":30}}}},"statementMap":{"1":{"start":{"line":23,"column":0},"end":{"line":167,"column":3}},"2":{"start":{"line":94,"column":8},"end":{"line":94,"column":22}},"3":{"start":{"line":95,"column":8},"end":{"line":95,"column":18}},"4":{"start":{"line":97,"column":8},"end":{"line":139,"column":9}},"5":{"start":{"line":100,"column":12},"end":{"line":116,"column":14}},"6":{"start":{"line":119,"column":12},"end":{"line":123,"column":15}},"7":{"start":{"line":126,"column":12},"end":{"line":138,"column":15}},"8":{"start":{"line":142,"column":8},"end":{"line":160,"column":9}},"9":{"start":{"line":143,"column":12},"end":{"line":159,"column":14}},"10":{"start":{"line":163,"column":8},"end":{"line":163,"column":25}},"11":{"start":{"line":165,"column":8},"end":{"line":165,"column":35}}},"branchMap":{"1":{"line":97,"type":"if","locations":[{"start":{"line":97,"column":8},"end":{"line":97,"column":8}},{"start":{"line":97,"column":8},"end":{"line":97,"column":8}}]},"2":{"line":100,"type":"binary-expr","locations":[{"start":{"line":100,"column":23},"end":{"line":100,"column":38}},{"start":{"line":100,"column":42},"end":{"line":116,"column":13}}]},"3":{"line":142,"type":"if","locations":[{"start":{"line":142,"column":8},"end":{"line":142,"column":8}},{"start":{"line":142,"column":8},"end":{"line":142,"column":8}}]}}};
}
__cov_3ngYgTb6MAkCzS6_ii_tJQ = __cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'];
__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['1']++;Ext.define('BasiGX.view.view.LayerSet',{extend:'Ext.view.View',xtype:'basigx-view-layerset',requires:['Ext.data.Store'],layerSetUrl:null,layerSetData:null,defaultImagePath:'classic/resources/img/themes/',demoThumb:'https://www.terrestris.de/wp-content/uploads/2014/03/'+'logo_terrestris_small3.png',width:400,height:300,singleSelect:true,cls:'img-chooser-view',overItemCls:'x-view-over',itemSelector:'div.thumb-wrap',tpl:null,initComponent:function(){__cov_3ngYgTb6MAkCzS6_ii_tJQ.f['1']++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['2']++;var me=this;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['3']++;var store;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['4']++;if(Ext.isEmpty(me.layerSetUrl)){__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['1'][0]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['5']++;var data=(__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['2'][0]++,me.layerSetData)||(__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['2'][1]++,[{'title':'Stadtkarte','name':'stadtkarte','thumb':me.demoThumb},{'title':'Verkehr','name':'verkehr','thumb':me.demoThumb},{'title':'Umwelt','name':'umwelt','thumb':me.demoThumb}]);__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['6']++;store=Ext.create('Ext.data.Store',{fields:['name','thumb','url','type'],sorters:'type',data:data});}else{__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['1'][1]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['7']++;store=Ext.create('Ext.data.Store',{autoLoad:true,fields:['name','title','thumb'],remoteSort:false,sorters:'type',proxy:{type:'ajax',url:me.layerSetUrl,reader:{type:'json'}}});}__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['8']++;if(Ext.isEmpty(me.tpl)){__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['3'][0]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['9']++;me.tpl=['<tpl for=".">','<div class="thumb-wrap">','<div class="thumb">','<tpl if="thumb.indexOf(\'http\') &gt;= 0">','<img src="{thumb}" />','<tpl else>','<img src="'+me.defaultImagePath,'{thumb}" />','</tpl>','</div>','<span>{title}</span>','</div>','</tpl>'];}else{__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['3'][1]++;}__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['10']++;me.store=store;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['11']++;this.callParent(arguments);}});
