
var __cov_3ngYgTb6MAkCzS6_ii_tJQ = (Function('return this'))();
if (!__cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__) { __cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__ = {}; }
__cov_3ngYgTb6MAkCzS6_ii_tJQ = __cov_3ngYgTb6MAkCzS6_ii_tJQ.__coverage__;
if (!(__cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'])) {
   __cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":86,"loc":{"start":{"line":86,"column":19},"end":{"line":86,"column":30}}}},"statementMap":{"1":{"start":{"line":23,"column":0},"end":{"line":157,"column":3}},"2":{"start":{"line":88,"column":8},"end":{"line":89,"column":18}},"3":{"start":{"line":91,"column":8},"end":{"line":129,"column":9}},"4":{"start":{"line":93,"column":12},"end":{"line":113,"column":15}},"5":{"start":{"line":116,"column":12},"end":{"line":128,"column":15}},"6":{"start":{"line":132,"column":8},"end":{"line":150,"column":9}},"7":{"start":{"line":133,"column":12},"end":{"line":149,"column":15}},"8":{"start":{"line":153,"column":8},"end":{"line":153,"column":25}},"9":{"start":{"line":155,"column":8},"end":{"line":155,"column":35}}},"branchMap":{"1":{"line":91,"type":"if","locations":[{"start":{"line":91,"column":8},"end":{"line":91,"column":8}},{"start":{"line":91,"column":8},"end":{"line":91,"column":8}}]},"2":{"line":132,"type":"if","locations":[{"start":{"line":132,"column":8},"end":{"line":132,"column":8}},{"start":{"line":132,"column":8},"end":{"line":132,"column":8}}]}}};
}
__cov_3ngYgTb6MAkCzS6_ii_tJQ = __cov_3ngYgTb6MAkCzS6_ii_tJQ['/home/travis/build/terrestris/BasiGX/src/view/view/LayerSet.js'];
__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['1']++;Ext.define('BasiGX.view.view.LayerSet',{extend:'Ext.view.View',xtype:'basigx-view-layerset',requires:['Ext.data.Store'],layerSetUrl:null,defaultImagePath:'classic/resources/img/themes/',demoThumb:'https://www.terrestris.de/wp-content/uploads/2014/03/'+'logo_terrestris_small3.png',width:400,height:300,singleSelect:true,cls:'img-chooser-view',overItemCls:'x-view-over',itemSelector:'div.thumb-wrap',tpl:null,initComponent:function(){__cov_3ngYgTb6MAkCzS6_ii_tJQ.f['1']++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['2']++;var me=this,store;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['3']++;if(Ext.isEmpty(me.layerSetUrl)){__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['1'][0]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['4']++;store=Ext.create('Ext.data.Store',{fields:['name','thumb','url','type'],sorters:'type',data:[{'title':'Stadtkarte','name':'stadtkarte','thumb':me.demoThumb},{'title':'Verkehr','name':'verkehr','thumb':me.demoThumb},{'title':'Umwelt','name':'umwelt','thumb':me.demoThumb}]});}else{__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['1'][1]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['5']++;store=Ext.create('Ext.data.Store',{autoLoad:true,fields:['name','title','thumb'],remoteSort:false,sorters:'type',proxy:{type:'ajax',url:me.layerSetUrl,reader:{type:'json'}}});}__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['6']++;if(Ext.isEmpty(me.tpl)){__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['2'][0]++;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['7']++;me.tpl=['<tpl for=".">','<div class="thumb-wrap">','<div class="thumb">','<tpl if="thumb.indexOf(\'http\') &gt;= 0">','<img src="{thumb}" />','<tpl else>','<img src="'+me.defaultImagePath,'{thumb}" />','</tpl>','</div>','<span>{title}</span>','</div>','</tpl>'];}else{__cov_3ngYgTb6MAkCzS6_ii_tJQ.b['2'][1]++;}__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['8']++;me.store=store;__cov_3ngYgTb6MAkCzS6_ii_tJQ.s['9']++;this.callParent(arguments);}});
