
var __cov_0wNnbVvswlPSEm1rSeUerQ = (Function('return this'))();
if (!__cov_0wNnbVvswlPSEm1rSeUerQ.__coverage__) { __cov_0wNnbVvswlPSEm1rSeUerQ.__coverage__ = {}; }
__cov_0wNnbVvswlPSEm1rSeUerQ = __cov_0wNnbVvswlPSEm1rSeUerQ.__coverage__;
if (!(__cov_0wNnbVvswlPSEm1rSeUerQ['/home/travis/build/terrestris/BasiGX/src/util/Url.js'])) {
   __cov_0wNnbVvswlPSEm1rSeUerQ['/home/travis/build/terrestris/BasiGX/src/util/Url.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/util/Url.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"(anonymous_1)","line":37,"loc":{"start":{"line":37,"column":23},"end":{"line":37,"column":42}}},"2":{"name":"(anonymous_2)","line":56,"loc":{"start":{"line":56,"column":26},"end":{"line":56,"column":37}}},"3":{"name":"(anonymous_3)","line":70,"loc":{"start":{"line":70,"column":30},"end":{"line":70,"column":41}}},"4":{"name":"(anonymous_4)","line":86,"loc":{"start":{"line":86,"column":27},"end":{"line":86,"column":38}}}},"statementMap":{"1":{"start":{"line":26,"column":0},"end":{"line":93,"column":3}},"2":{"start":{"line":38,"column":12},"end":{"line":38,"column":69}},"3":{"start":{"line":39,"column":12},"end":{"line":39,"column":67}},"4":{"start":{"line":40,"column":12},"end":{"line":40,"column":22}},"5":{"start":{"line":41,"column":12},"end":{"line":43,"column":13}},"6":{"start":{"line":42,"column":16},"end":{"line":42,"column":59}},"7":{"start":{"line":44,"column":12},"end":{"line":44,"column":25}},"8":{"start":{"line":57,"column":12},"end":{"line":57,"column":38}},"9":{"start":{"line":58,"column":12},"end":{"line":58,"column":71}},"10":{"start":{"line":71,"column":12},"end":{"line":71,"column":38}},"11":{"start":{"line":72,"column":12},"end":{"line":72,"column":53}},"12":{"start":{"line":73,"column":12},"end":{"line":75,"column":17}},"13":{"start":{"line":77,"column":12},"end":{"line":77,"column":40}},"14":{"start":{"line":87,"column":12},"end":{"line":87,"column":38}},"15":{"start":{"line":88,"column":12},"end":{"line":88,"column":63}},"16":{"start":{"line":89,"column":12},"end":{"line":89,"column":27}}},"branchMap":{"1":{"line":39,"type":"binary-expr","locations":[{"start":{"line":39,"column":38},"end":{"line":39,"column":41}},{"start":{"line":39,"column":45},"end":{"line":39,"column":65}}]},"2":{"line":41,"type":"if","locations":[{"start":{"line":41,"column":12},"end":{"line":41,"column":12}},{"start":{"line":41,"column":12},"end":{"line":41,"column":12}}]}}};
}
__cov_0wNnbVvswlPSEm1rSeUerQ = __cov_0wNnbVvswlPSEm1rSeUerQ['/home/travis/build/terrestris/BasiGX/src/util/Url.js'];
__cov_0wNnbVvswlPSEm1rSeUerQ.s['1']++;Ext.define('BasiGX.util.Url',{statics:{getParamValue:function(key,url){__cov_0wNnbVvswlPSEm1rSeUerQ.f['1']++;__cov_0wNnbVvswlPSEm1rSeUerQ.s['2']++;var re=new RegExp('[\\?&]'+(key+'')+'=([^&#]*)');__cov_0wNnbVvswlPSEm1rSeUerQ.s['3']++;var regexResult=re.exec((__cov_0wNnbVvswlPSEm1rSeUerQ.b['1'][0]++,url)||(__cov_0wNnbVvswlPSEm1rSeUerQ.b['1'][1]++,window.location.href));__cov_0wNnbVvswlPSEm1rSeUerQ.s['4']++;var value;__cov_0wNnbVvswlPSEm1rSeUerQ.s['5']++;if(regexResult){__cov_0wNnbVvswlPSEm1rSeUerQ.b['2'][0]++;__cov_0wNnbVvswlPSEm1rSeUerQ.s['6']++;value=decodeURIComponent(regexResult[1]);}else{__cov_0wNnbVvswlPSEm1rSeUerQ.b['2'][1]++;}__cov_0wNnbVvswlPSEm1rSeUerQ.s['7']++;return value;},getCurrentAppUrl:function(){__cov_0wNnbVvswlPSEm1rSeUerQ.f['2']++;__cov_0wNnbVvswlPSEm1rSeUerQ.s['8']++;var loc=window.location;__cov_0wNnbVvswlPSEm1rSeUerQ.s['9']++;return loc.protocol+'//'+loc.host+loc.pathname+'?';},getWebProjectBaseUrl:function(){__cov_0wNnbVvswlPSEm1rSeUerQ.f['3']++;__cov_0wNnbVvswlPSEm1rSeUerQ.s['10']++;var loc=window.location;__cov_0wNnbVvswlPSEm1rSeUerQ.s['11']++;var url=loc.protocol+'//'+loc.host;__cov_0wNnbVvswlPSEm1rSeUerQ.s['12']++;var webProjectName=window.location.pathname.match(/^\/[\w\-]*\/?/)[0];__cov_0wNnbVvswlPSEm1rSeUerQ.s['13']++;return url+webProjectName;},getProjectBaseUrl:function(){__cov_0wNnbVvswlPSEm1rSeUerQ.f['4']++;__cov_0wNnbVvswlPSEm1rSeUerQ.s['14']++;var loc=window.location;__cov_0wNnbVvswlPSEm1rSeUerQ.s['15']++;var baseUrl=loc.protocol+'//'+loc.host+'/';__cov_0wNnbVvswlPSEm1rSeUerQ.s['16']++;return baseUrl;}}});
