
var __cov_$v9CMxLezUMlQnzRrDbWqg = (Function('return this'))();
if (!__cov_$v9CMxLezUMlQnzRrDbWqg.__coverage__) { __cov_$v9CMxLezUMlQnzRrDbWqg.__coverage__ = {}; }
__cov_$v9CMxLezUMlQnzRrDbWqg = __cov_$v9CMxLezUMlQnzRrDbWqg.__coverage__;
if (!(__cov_$v9CMxLezUMlQnzRrDbWqg['/home/travis/build/terrestris/BasiGX/src/view/button/AddWms.js'])) {
   __cov_$v9CMxLezUMlQnzRrDbWqg['/home/travis/build/terrestris/BasiGX/src/view/button/AddWms.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/button/AddWms.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{"1":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":123,"loc":{"start":{"line":123,"column":17},"end":{"line":123,"column":28}}}},"statementMap":{"1":{"start":{"line":24,"column":0},"end":{"line":148,"column":3}},"2":{"start":{"line":124,"column":12},"end":{"line":124,"column":75}},"3":{"start":{"line":125,"column":12},"end":{"line":145,"column":13}},"4":{"start":{"line":127,"column":16},"end":{"line":137,"column":18}},"5":{"start":{"line":139,"column":16},"end":{"line":139,"column":65}},"6":{"start":{"line":140,"column":16},"end":{"line":140,"column":61}},"7":{"start":{"line":142,"column":16},"end":{"line":142,"column":69}},"8":{"start":{"line":144,"column":16},"end":{"line":144,"column":47}}},"branchMap":{"1":{"line":125,"type":"if","locations":[{"start":{"line":125,"column":12},"end":{"line":125,"column":12}},{"start":{"line":125,"column":12},"end":{"line":125,"column":12}}]}}};
}
__cov_$v9CMxLezUMlQnzRrDbWqg = __cov_$v9CMxLezUMlQnzRrDbWqg['/home/travis/build/terrestris/BasiGX/src/view/button/AddWms.js'];
__cov_$v9CMxLezUMlQnzRrDbWqg.s['1']++;Ext.define('BasiGX.view.button.AddWms',{extend:'BasiGX.view.button.Base',xtype:'basigx-button-addwms',requires:['Ext.window.Window','Ext.app.ViewModel','BasiGX.view.form.AddWms','BasiGX.util.Animate'],viewModel:{data:{tooltip:'WMS hinzufügen',text:'WMS <span style="font-size: 1.7em; '+'font-weight: normal;">\u2295</span>',windowTitle:'WMS hinzufügen',documentation:'<h2>WMS hinzufügen</h2>\u2022 Ein Klick auf den '+'Button öffnet ein Fenster, in dem Sie mit Hilfe einer '+'WMS-URL einen beliebigen Kartendienst der Karte hinzufügen '+'können.'}},bind:{text:'{text}'},liveDemoConfig:[{moveMouseTo:{component:'basigx-button-addwms',moveDuration:2000}},{clickOnButton:'basigx-button-addwms'},{moveMouseTo:{component:'window[name=add-wms-window] textfield[name=url]',moveDuration:2000}},{enterText:{component:'window[name=add-wms-window] textfield[name=url]',text:'https://ows.terrestris.de/osm/service',waitAfter:3500}},{moveMouseTo:'window[name=add-wms-window] button[name=requestLayersBtn]'},{clickOnButton:{component:'window[name=add-wms-window] button[name=requestLayersBtn]',waitAfter:3000}},{scrollTo:{component:'window[name=add-wms-window] form',target:{x:0,y:999,animate:true}}},{moveMouseTo:'window[name=add-wms-window] button[name=add-checked-layers]'},{destroy:'window[name=add-wms-window]'}],config:{windowConfig:{},handler:function(){__cov_$v9CMxLezUMlQnzRrDbWqg.f['1']++;__cov_$v9CMxLezUMlQnzRrDbWqg.s['2']++;var win=Ext.ComponentQuery.query('[name=add-wms-window]')[0];__cov_$v9CMxLezUMlQnzRrDbWqg.s['3']++;if(!win){__cov_$v9CMxLezUMlQnzRrDbWqg.b['1'][0]++;__cov_$v9CMxLezUMlQnzRrDbWqg.s['4']++;var windowConfig={name:'add-wms-window',title:this.getViewModel().get('windowTitle'),width:500,height:400,layout:'fit',constrain:true,items:[{xtype:'basigx-form-addwms'}]};__cov_$v9CMxLezUMlQnzRrDbWqg.s['5']++;var windowConfigToApply=this.getWindowConfig();__cov_$v9CMxLezUMlQnzRrDbWqg.s['6']++;Ext.apply(windowConfig,windowConfigToApply);__cov_$v9CMxLezUMlQnzRrDbWqg.s['7']++;Ext.create('Ext.window.Window',windowConfig).show();}else{__cov_$v9CMxLezUMlQnzRrDbWqg.b['1'][1]++;__cov_$v9CMxLezUMlQnzRrDbWqg.s['8']++;BasiGX.util.Animate.shake(win);}}}});
