
var __cov_D3QXK2GJ8YTeJoCrtetZrQ = (Function('return this'))();
if (!__cov_D3QXK2GJ8YTeJoCrtetZrQ.__coverage__) { __cov_D3QXK2GJ8YTeJoCrtetZrQ.__coverage__ = {}; }
__cov_D3QXK2GJ8YTeJoCrtetZrQ = __cov_D3QXK2GJ8YTeJoCrtetZrQ.__coverage__;
if (!(__cov_D3QXK2GJ8YTeJoCrtetZrQ['/home/travis/build/terrestris/BasiGX/src/view/button/Hsi.js'])) {
   __cov_D3QXK2GJ8YTeJoCrtetZrQ['/home/travis/build/terrestris/BasiGX/src/view/button/Hsi.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/button/Hsi.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"(anonymous_1)","line":81,"loc":{"start":{"line":81,"column":17},"end":{"line":81,"column":28}}},"2":{"name":"(anonymous_2)","line":90,"loc":{"start":{"line":90,"column":17},"end":{"line":90,"column":28}}},"3":{"name":"(anonymous_3)","line":98,"loc":{"start":{"line":98,"column":18},"end":{"line":98,"column":29}}},"4":{"name":"(anonymous_4)","line":117,"loc":{"start":{"line":117,"column":22},"end":{"line":117,"column":39}}}},"statementMap":{"1":{"start":{"line":23,"column":0},"end":{"line":124,"column":3}},"2":{"start":{"line":82,"column":12},"end":{"line":82,"column":53}},"3":{"start":{"line":83,"column":12},"end":{"line":83,"column":32}},"4":{"start":{"line":91,"column":8},"end":{"line":91,"column":35}},"5":{"start":{"line":92,"column":8},"end":{"line":92,"column":28}},"6":{"start":{"line":99,"column":8},"end":{"line":104,"column":9}},"7":{"start":{"line":100,"column":12},"end":{"line":100,"column":48}},"8":{"start":{"line":102,"column":12},"end":{"line":103,"column":42}},"9":{"start":{"line":105,"column":8},"end":{"line":105,"column":50}},"10":{"start":{"line":118,"column":8},"end":{"line":118,"column":22}},"11":{"start":{"line":119,"column":8},"end":{"line":119,"column":25}},"12":{"start":{"line":121,"column":8},"end":{"line":121,"column":78}},"13":{"start":{"line":122,"column":8},"end":{"line":122,"column":44}}},"branchMap":{"1":{"line":99,"type":"if","locations":[{"start":{"line":99,"column":8},"end":{"line":99,"column":8}},{"start":{"line":99,"column":8},"end":{"line":99,"column":8}}]},"2":{"line":102,"type":"cond-expr","locations":[{"start":{"line":102,"column":45},"end":{"line":102,"column":65}},{"start":{"line":103,"column":16},"end":{"line":103,"column":40}}]}}};
}
__cov_D3QXK2GJ8YTeJoCrtetZrQ = __cov_D3QXK2GJ8YTeJoCrtetZrQ['/home/travis/build/terrestris/BasiGX/src/view/button/Hsi.js'];
__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['1']++;Ext.define('BasiGX.view.button.Hsi',{extend:'BasiGX.view.button.Base',xtype:'basigx-button-hsi',requires:['Ext.app.ViewModel','BasiGX.util.Map'],viewModel:{data:{tooltip:'Informationsabfrage',text:null,documentation:'<h2>Informationsabfrage</h2>\u2022 Ein Klick auf den '+'Button aktiviert bzw. deaktiviert die Informationsabfrage '+'in der Karte.<br>\u2022 Wenn Sie sich bei aktiviertem Werkzeug '+'mit der Maus über ein abfragbares Kartenthema befinden, '+'wird die Information zu diesem Objekt in einem Fenster '+'dargestellt'}},bind:{text:'{text}'},glyph:'xf05a@FontAwesome',html:'<i class="fa fa-info-circle fa-2x"></i>',enableToggle:true,buttonPressed:true,config:{mapPanelXType:null,handler:function(){__cov_D3QXK2GJ8YTeJoCrtetZrQ.f['1']++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['2']++;this.buttonPressed=!this.buttonPressed;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['3']++;this.toggleButton();}},constructor:function(){__cov_D3QXK2GJ8YTeJoCrtetZrQ.f['2']++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['4']++;this.callParent(arguments);__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['5']++;this.toggleButton();},toggleButton:function(){__cov_D3QXK2GJ8YTeJoCrtetZrQ.f['3']++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['6']++;if(this.setPressed){__cov_D3QXK2GJ8YTeJoCrtetZrQ.b['1'][0]++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['7']++;this.setPressed(this.buttonPressed);}else{__cov_D3QXK2GJ8YTeJoCrtetZrQ.b['1'][1]++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['8']++;this.setCls(this.buttonPressed?(__cov_D3QXK2GJ8YTeJoCrtetZrQ.b['2'][0]++,this.getPressedCls()):(__cov_D3QXK2GJ8YTeJoCrtetZrQ.b['2'][1]++,'basigx-map-tool-button'));}__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['9']++;this.setControlStatus(this.buttonPressed);},setControlStatus:function(status){__cov_D3QXK2GJ8YTeJoCrtetZrQ.f['4']++;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['10']++;var me=this;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['11']++;var mapComponent;__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['12']++;mapComponent=BasiGX.util.Map.getMapComponent(me.getMapPanelXType());__cov_D3QXK2GJ8YTeJoCrtetZrQ.s['13']++;mapComponent.setPointerRest(status);}});
