
var __cov_GpplK_WRcJT7TGll46UASw = (Function('return this'))();
if (!__cov_GpplK_WRcJT7TGll46UASw.__coverage__) { __cov_GpplK_WRcJT7TGll46UASw.__coverage__ = {}; }
__cov_GpplK_WRcJT7TGll46UASw = __cov_GpplK_WRcJT7TGll46UASw.__coverage__;
if (!(__cov_GpplK_WRcJT7TGll46UASw['/home/travis/build/terrestris/BasiGX/src/view/button/Permalink.js'])) {
   __cov_GpplK_WRcJT7TGll46UASw['/home/travis/build/terrestris/BasiGX/src/view/button/Permalink.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/button/Permalink.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0},"b":{"1":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":75,"loc":{"start":{"line":75,"column":17},"end":{"line":75,"column":28}}}},"statementMap":{"1":{"start":{"line":23,"column":0},"end":{"line":92,"column":3}},"2":{"start":{"line":76,"column":12},"end":{"line":76,"column":77}},"3":{"start":{"line":77,"column":12},"end":{"line":89,"column":13}},"4":{"start":{"line":78,"column":16},"end":{"line":86,"column":26}},"5":{"start":{"line":88,"column":16},"end":{"line":88,"column":47}}},"branchMap":{"1":{"line":77,"type":"if","locations":[{"start":{"line":77,"column":12},"end":{"line":77,"column":12}},{"start":{"line":77,"column":12},"end":{"line":77,"column":12}}]}}};
}
__cov_GpplK_WRcJT7TGll46UASw = __cov_GpplK_WRcJT7TGll46UASw['/home/travis/build/terrestris/BasiGX/src/view/button/Permalink.js'];
__cov_GpplK_WRcJT7TGll46UASw.s['1']++;Ext.define('BasiGX.view.button.Permalink',{extend:'BasiGX.view.button.Base',xtype:'basigx-button-permalink',requires:['Ext.window.Window','Ext.app.ViewModel','BasiGX.view.form.Permalink','BasiGX.util.Animate','BasiGX.util.Application'],viewModel:{data:{tooltip:'Permalink erzeugen',text:'Permalink',windowTitle:'Link zur Anwendung',documentation:'<h2>Permalink erzeugen</h2>\u2022 Ein Klick auf '+'den Button öffnet ein Fenster, in dem ein Permalink erzeugt '+'werden kann. Dieser Link kann benutzt werden, um die '+'Applikation in einem vordefinierten Zustand, wie z.B. '+'Zentrum der Karte oder sichtbare Themen, zu öffnen.'}},liveDemoConfig:[{moveMouseTo:'basigx-button-permalink'},{clickOnButton:'basigx-button-permalink'},{moveMouseTo:'window[name=permalink-window]'},{destroy:'window[name=permalink-window]'}],bind:{text:'{text}'},config:{handler:function(){__cov_GpplK_WRcJT7TGll46UASw.f['1']++;__cov_GpplK_WRcJT7TGll46UASw.s['2']++;var win=Ext.ComponentQuery.query('[name=permalink-window]')[0];__cov_GpplK_WRcJT7TGll46UASw.s['3']++;if(!win){__cov_GpplK_WRcJT7TGll46UASw.b['1'][0]++;__cov_GpplK_WRcJT7TGll46UASw.s['4']++;Ext.create('Ext.window.Window',{name:'permalink-window',constrain:true,title:this.getViewModel().get('windowTitle'),layout:'fit',items:[{xtype:'basigx-form-permalink'}]}).show();}else{__cov_GpplK_WRcJT7TGll46UASw.b['1'][1]++;__cov_GpplK_WRcJT7TGll46UASw.s['5']++;BasiGX.util.Animate.shake(win);}}}});
