
var __cov_QJFGxaSnnf1q0szJKZmC2g = (Function('return this'))();
if (!__cov_QJFGxaSnnf1q0szJKZmC2g.__coverage__) { __cov_QJFGxaSnnf1q0szJKZmC2g.__coverage__ = {}; }
__cov_QJFGxaSnnf1q0szJKZmC2g = __cov_QJFGxaSnnf1q0szJKZmC2g.__coverage__;
if (!(__cov_QJFGxaSnnf1q0szJKZmC2g['/home/travis/build/terrestris/BasiGX/src/view/button/ZoomOut.js'])) {
   __cov_QJFGxaSnnf1q0szJKZmC2g['/home/travis/build/terrestris/BasiGX/src/view/button/ZoomOut.js'] = {"path":"/home/travis/build/terrestris/BasiGX/src/view/button/ZoomOut.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":76,"loc":{"start":{"line":76,"column":17},"end":{"line":76,"column":28}}}},"statementMap":{"1":{"start":{"line":23,"column":0},"end":{"line":105,"column":3}},"2":{"start":{"line":77,"column":12},"end":{"line":77,"column":26}},"3":{"start":{"line":78,"column":12},"end":{"line":78,"column":33}},"4":{"start":{"line":79,"column":12},"end":{"line":79,"column":23}},"5":{"start":{"line":80,"column":12},"end":{"line":80,"column":21}},"6":{"start":{"line":83,"column":12},"end":{"line":85,"column":13}},"7":{"start":{"line":84,"column":16},"end":{"line":84,"column":67}},"8":{"start":{"line":87,"column":12},"end":{"line":87,"column":37}},"9":{"start":{"line":90,"column":12},"end":{"line":102,"column":13}},"10":{"start":{"line":91,"column":16},"end":{"line":94,"column":19}},"11":{"start":{"line":95,"column":16},"end":{"line":95,"column":41}},"12":{"start":{"line":96,"column":16},"end":{"line":96,"column":65}},"13":{"start":{"line":98,"column":16},"end":{"line":101,"column":19}}},"branchMap":{"1":{"line":83,"type":"if","locations":[{"start":{"line":83,"column":12},"end":{"line":83,"column":12}},{"start":{"line":83,"column":12},"end":{"line":83,"column":12}}]},"2":{"line":90,"type":"if","locations":[{"start":{"line":90,"column":12},"end":{"line":90,"column":12}},{"start":{"line":90,"column":12},"end":{"line":90,"column":12}}]}}};
}
__cov_QJFGxaSnnf1q0szJKZmC2g = __cov_QJFGxaSnnf1q0szJKZmC2g['/home/travis/build/terrestris/BasiGX/src/view/button/ZoomOut.js'];
__cov_QJFGxaSnnf1q0szJKZmC2g.s['1']++;Ext.define('BasiGX.view.button.ZoomOut',{extend:'BasiGX.view.button.Base',xtype:'basigx-button-zoomout',requires:['Ext.app.ViewModel','BasiGX.util.Map'],viewModel:{data:{tooltip:'Herauszoomen',text:null,documentation:'<h2>Herauszoomen</h2>\u2022 Ein Klick auf den Button '+'verkleinert die Karte um eine Zoomstufe.'}},bind:{text:'{text}'},olMap:null,glyph:'xf010@FontAwesome',html:'<i class="fa fa-search-minus fa-2x"></i>',liveDemoConfig:[{moveMouseTo:'basigx-button-zoomout'},{clickOnButton:'basigx-button-zoomout'}],config:{handler:function(){__cov_QJFGxaSnnf1q0szJKZmC2g.f['1']++;__cov_QJFGxaSnnf1q0szJKZmC2g.s['2']++;var me=this;__cov_QJFGxaSnnf1q0szJKZmC2g.s['3']++;var olMap=me.olMap;__cov_QJFGxaSnnf1q0szJKZmC2g.s['4']++;var olView;__cov_QJFGxaSnnf1q0szJKZmC2g.s['5']++;var zoom;__cov_QJFGxaSnnf1q0szJKZmC2g.s['6']++;if(Ext.isEmpty(olMap)){__cov_QJFGxaSnnf1q0szJKZmC2g.b['1'][0]++;__cov_QJFGxaSnnf1q0szJKZmC2g.s['7']++;olMap=BasiGX.util.Map.getMapComponent().getMap();}else{__cov_QJFGxaSnnf1q0szJKZmC2g.b['1'][1]++;}__cov_QJFGxaSnnf1q0szJKZmC2g.s['8']++;olView=olMap.getView();__cov_QJFGxaSnnf1q0szJKZmC2g.s['9']++;if(ol.animation){__cov_QJFGxaSnnf1q0szJKZmC2g.b['2'][0]++;__cov_QJFGxaSnnf1q0szJKZmC2g.s['10']++;zoom=ol.animation.zoom({resolution:olView.getResolution(),duration:500});__cov_QJFGxaSnnf1q0szJKZmC2g.s['11']++;olMap.beforeRender(zoom);__cov_QJFGxaSnnf1q0szJKZmC2g.s['12']++;olView.setResolution(olView.getResolution()*2);}else{__cov_QJFGxaSnnf1q0szJKZmC2g.b['2'][1]++;__cov_QJFGxaSnnf1q0szJKZmC2g.s['13']++;olView.animate({resolution:olView.getResolution()*2,duration:500});}}}});
